apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasks-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:SimBienvenueHoulBoumi/tasks-cicd.git
    targetRevision: main
    path: kubernetes/tasks        # adapte si ton dossier manifests est différent
  destination:
    server: https://kubernetes.default.svc
    namespace: task-rest-api      # namespace où ton app tourne
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true